name: Github Actions Demo
on: 
  workflow_dispatch:
  push:
  
jobs:
  Example-Actions-Job:
    name: Exploring Github Actions
    runs-on: ubuntu-latest
    steps:
    - run: echo "Payload field is ${{ github.event.client_payload.mydata }}"
    # Display the event that triggered the workflow
    - run: echo "The job was triggerd by a ${{ github.event_name }} event."
    
    # Runner information
    - run: echo "This job is running on ${{ runner.os }} server hosted by GitHub."
    
    - name: Detect Node version
      run: | 
        node --version
     
    - name: Detect Npm version
      run: | 
        npm --version
    - name: Download Node 20 Version
      run: |
        curl -o node-v20.tar.xz https://nodejs.org/dist/v20.9.0/node-v20.9.0-linux-x64.tar.xz
    - name: Extract Node 
      run: |
        mkdir sw 
        tar -C sw -xf node-v20.tar.xz
        ls -ltr ${{ github.workspace }}
        cd sw/node-v20.9.0-linux-x64/bin
        ls -ltr
    - name: Detect Node20 version
      run: | 
        export PATH=/home/runner/work/github-actions23/github-actions23/sw/node-v20.9.0-linux-x64/bin:$PATH
        npm --version
        node --version
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build 
      run: | 
        export PATH=/home/runner/work/github-actions23/github-actions23/sw/node-v20.9.0-linux-x64/bin:$PATH
        curl -uraju4cloud:AP2PoNKU4AAE8jMYqWRq8URGHwr "https://selfeducation.jfrog.io/artifactory/api/npm/npm-yoglib-local/auth/jfrog" > .npmrc
        cat .npmrc
        npm install 
        npm run build
        npm pack
        rm -f .npmrcgit restore 
    - name: Run Action
      uses: ./
      id: hello
      with:
        who-to-greet: 'Yogendra Prasad'

   # - name: Publish
   #     export PATH=/home/runner/work/github-actions23/github-actions23/sw/node-v20.9.0-linux-x64/bin:$PATH
   #     curl -uraju4cloud:AP2PoNKU4AAE8jMYqWRq8URGHwr "https://selfeducation.jfrog.io/artifactory/api/npm/npm-yoglib-local/auth/jfrog" > .npmrc
   #     cat .npmrc
        #npm publish --registry https://selfeducation.jfrog.io/artifactory/api/npm/npm-yoglib-local/
