name: Looping Uses Action Example

on:
  workflow_dispatch:
  
jobs:
  loop_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [v1, v2, v3]  # List of versions to iterate over

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Loop Steps
        run: |
          for version in ${{ matrix.version }}; do
            echo "Running with version $version"
            # Include the action within the loop
            uses: actions/setup-node@$version
            with:
              node-version: '14'
          done
