name: Github Actions Demo
on: 
  workflow_dispatch:
  push:
  
jobs:
  Example-Actions-Job:
    env:
      ARTI_REPO: 'student-home-nuget'
    name: Exploring Github Actions
    runs-on: ubuntu-latest
    steps:
    - run: echo "Payload field is ${{ github.event.client_payload.mydata }}"
    # Display the event that triggered the workflow
    - run: echo "The job was triggerd by a ${{ github.event_name }} event."
    
    # Runner information
    - run: echo "This job is running on ${{ runner.os }} server hosted by GitHub."
    
    - name: Detect Node version
      run: | 
        node --version
     
    - name: Detect Npm version
      run: | 
        npm --version
    - name: Download Node 20 Version
      run: |
        curl -o node-v20.tar.xz https://nodejs.org/dist/v20.9.0/node-v20.9.0-linux-x64.tar.xz
    - name: Extract Node 
      run: |
        mkdir sw 
        tar -C sw -xf node-v20.tar.xz
        ls -ltr ${{ github.workspace }}
        cd sw/node-v20.9.0-linux-x64/bin
        ls -ltr
    - name: Detect Node20 version
      run: | 
        export PATH=/home/runner/work/github-actions23/github-actions23/sw/node-v20.9.0-linux-x64/bin:$PATH
        npm --version
        node --version
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: '7.0'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Detect Package Name
      id: read-json
      run: |
        echo "packageConfig<<EOF" >> $GITHUB_OUTPUT
        cat ./package.json >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    - name: Print OUtput
      env: 
        PACKAGE_NAME: ${{ fromJson(steps.read-json.outputs.packageConfig).name }}
        PACKAGE_VERSION: ${{ fromJson(steps.read-json.outputs.packageConfig).version }}
      run: |
        echo "${{ fromJson(steps.read-json.outputs.packageConfig).version }}"
        echo "${{ fromJson(steps.read-json.outputs.packageConfig).name }}"
    - name: Build
      env: 
        FILETOPUB: ${{ env.PACKAGE_NAME }}. ${{ env.PACKAGE_VERSION }} .tgz
      run: | 
        echo "Package to Publish is ${{ fromJson(steps.read-json.outputs.packageConfig).name }}.${{ fromJson(steps.read-json.outputs.packageConfig).version }}.tgz"
        export PATH=/home/runner/work/github-actions23/github-actions23/sw/node-v20.9.0-linux-x64/bin:$PATH
        #curl -uraju4cloud:AP2PoNKU4AAE8jMYqWRq8URGHwr "https://studentwf.jfrog.io/artifactory/api/npm/npm-yoglib-local/auth/jfrog" > .npmrc
        curl -uraju4cloud1:AP7L5WkZYceUnSoVYZuGq6rRyi4 "https://studentwf.jfrog.io/artifactory/api/npm/student-home-npm/auth/jfrog" > .npmrc
        mkdir npm
        mv -f .npmrc npm/
        npm install --userconfig npm/.npmrc
        npm run build
        npm pack
        rm -f npm/.npmrc 
    
    - name: Build Dotnet Component
      id: dotnet-build
      run : |
        dotnet msbuild 'dotnetProj/build.proj'
        
    - name: Zip Dotnet Artifacts
      id: zip-dotnet-artifacts
      run: |
        zip -r dotnet-artifacts.zip dotnetProj/WebApp/bin/Debug/net7.0

    - name: Resolve Repository Name
      run: |
        ARTI_NPM_REPO=$( echo $ARTI_REPO | sed 's/nuget/npm')
        echo "ARTI_NPM_REPO=$ARTI_NPM_REPO" >> $GITHUB_ENV

        ARTI_GENERIC_REPO=$( echo $ARTI_REPO | sed 's/nuget/generic')
        echo "ARTI_GENERIC_REPO=$ARTI_GENERIC_REPO" >> $GITHUB_ENV
    
    - name: Fetch Artifacts Name
      id: fetch-artifacts
      run : |
        
        file_extensions=("zip" "tgz" "nupkg" "csproj" "abc" "json")
        
        for ext in "${file_extensions[@]}"; do
          files=$(find . -maxdepth 5 -type f -name "*.$ext")
          if [ -n "$files" ]; then
            case $ext in
              "zip")
                destination_folder="artifactsZip"
                zipFileName="artifactsZip.zip"
                echo "zipTypeArtifact-exists=true" >> $GITHUB_OUTPUT
                ;;
              "tgz")
                destination_folder="artifactsTgz"
                zipFileName="artifactsTgz.zip"
                echo "tgzTypeArtifact-exists=true" >> $GITHUB_OUTPUT
                ;;
              "nupkg")
                destination_folder="artifactsNupkg"
                zipFileName="artifactsNupkg.zip"
                echo "nugetTypeArtifact-exists=true" >> $GITHUB_OUTPUT
               ;;
              "csproj")
                destination_folder="artifactsCsproj"
                zipFileName="artifactsCsproj.zip"
                echo "csprojTypeArtifact-exists=true" >> $GITHUB_OUTPUT
               ;;
              "abc")
                destination_folder="artifactsAbc"
                zipFileName="artifactsAbc.zip"
                echo "abcTypeArtifact-exists=true" >> $GITHUB_OUTPUT
               ;;
              "json")
                destination_folder="artifactsJson"
                zipFileName="artifactsJson.zip"
                echo "jsonTypeArtifact-exists=true" >> $GITHUB_OUTPUT
               ;;
            esac
            mkdir -p "$destination_folder"
            for file in $files; do
              cp "$file" "$destination_folder"
            done
            zip -r "$zipFileName" "$destination_folder"
          fi
        done
        
    - name: Publish Npm
      if: steps.fetch-artifacts.outputs.tgzTypeArtifact-exists == 'true'
      run: |
        curl -v --user raju4cloud1:AP6p63fJbtFZ9i72CQiJALhxZdu -T artifactsTgz.zip -X PUT -H 'X-Explode-Archive: true' "https://studenthome.jfrog.io/artifactory/${{env.ARTI_NPM_REPO }}/${{ fromJson(steps.read-json.outputs.packageConfig).version }}/"
 
    - name: Publish Nuget
      if: steps.fetch-artifacts.outputs.nugetTypeArtifact-exists == 'true'
      run: | 
        curl -v --user raju4cloud1:AP6p63fJbtFZ9i72CQiJALhxZdu -T artifactsNupkg.zip -X PUT -H 'X-Explode-Archive: true' "https://studenthome.jfrog.io/artifactory/${{env.ARTI_REPO }}/${{ fromJson(steps.read-json.outputs.packageConfig).version }}/"

    - name: Publish Generic (zip)
      if: steps.fetch-artifacts.outputs.zipTypeArtifact-exists == 'true'
      run: | 
        curl -v --user raju4cloud1:AP6p63fJbtFZ9i72CQiJALhxZdu -T artifactsZip.zip -X PUT -H 'X-Explode-Archive: true' "https://studenthome.jfrog.io/artifactory/${{ env.ARTI_GENERIC_REPO }}/${{ fromJson(steps.read-json.outputs.packageConfig).version }}/"

    - name: Publish Generic (Json)
      if: steps.fetch-artifacts.outputs.jsonTypeArtifact-exists == 'true'
      run: | 
        curl -v --user raju4cloud1:AP6p63fJbtFZ9i72CQiJALhxZdu -T artifactsJson.zip -X PUT -H 'X-Explode-Archive: true' "https://studenthome.jfrog.io/artifactory${{ env.ARTI_GENERIC_REPO }}/${{ fromJson(steps.read-json.outputs.packageConfig).version }}/"
   
    - name: Publish Generic (CSProj)
      if: steps.fetch-artifacts.outputs.CsprojTypeArtifact-exists == 'true'
      run: | 
        curl -v --user raju4cloud1:AP6p63fJbtFZ9i72CQiJALhxZdu -T artifactsCsproj.zip -X PUT -H 'X-Explode-Archive: true' "https://studenthome.jfrog.io/artifactory/${{ env.ARTI_GENERIC_REPO }}/${{ fromJson(steps.read-json.outputs.packageConfig).version }}/"
