name: Github Actions Demo(2)
on: 
  workflow_dispatch:
    inputs:
      your_input_name:
        description: 'Description of your input'
        required: true
        default: 'default_value'
  
jobs:
  Set-CLI-Paramater:
    name: Exploring Github Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display Input
        run: echo "Your input is ${{ inputs.your_input_name }}"