name: Github Actions Demo
on: 
  workflow_dispatch:
  
jobs:
  Example-Actions-Job:
    name: Exploring Github Actions
    runs-on: ubuntu-latest
    steps:
    - run: echo "Payload field is ${{ github.event.client_payload.mydata }}"
    # Display the event that triggered the workflow
    - run: echo "The job was triggerd by a ${{ github.event_name }} event."
    
    # Runner information
    - run: echo "This job is running on ${{ runner.os }} server hosted by GitHub."
    
    - name: Detect Node version
      run: | 
        node --version
     
    - name: Detect Npm version
      run: | 
        npm --version
    - name: Download Node 20 Version
      run: |
        curl -o node-v20.tar.xz https://nodejs.org/dist/v20.9.0/node-v20.9.0-linux-arm64.tar.xz
    - name: Extract Node 
      run: |
        mkdir sw 
        tar -C sw -xf node-v20.tar.xz
    - name: Detect Node20 version
      run: | 
        ./sw/node --version
     
    - name: Detect Npm20 version
      run: | 
        ./sw/npm --version
