name: Github Actions Demo(2)
on: 
  workflow_dispatch:
    inputs:
      dotnet_build_params:
        description: 'Dotnet Build Params'
        required: false
        default: ''

      your_input_name:
        description: 'Description of your input'
        required: true
        default: 'default_value'
  
jobs:
  Set-CLI-Paramater:
    name: Exploring Github Actions
    runs-on: ubuntu-latest
    steps:
      - name: Display Input
        run: echo "Your input is ${{ inputs.dotnet_build_params }}"
      
      - name: Prepare Dotnet Command
        id: prepare-dotnet-command
        run: |
          dotnetCommand="dotnet build"
          if [ -n "${{ inputs.dotnet_build_params}}" ]; then
            dotnetCommand="$dotnetCommand ${{ inputs.dotnet_build_params}}"
          fi
          echo "dotnetCommand=$dotnetCommand" >> $GITHUB_OUTPUT
      - name: Validate Dotnet Command
        run: |
          echo "${{ steps.prepare-dotnet-command.outputs.dotnetCommand}}"