name: SomeExecution
run-name: Executing 
on: 
  workflow_dispatch:
    inputs:
      params1:
        description: 'Params1'
        required: false
        default: ''
      params2:
         description: 'Params2'
         required: false
         default: ''

      your_input_name:
        description: 'Description of your input'
        required: true
        default: 'default_value'
jobs:
  MyTest:
    runs-on: ubuntu-latest
    steps:
    - id: Sameple-step
      name: Sample Step
      run: |
        artifacts=home1.movie.sirir.apple.20302456.09.89.01.zip|home1.movie.sirir.apple.20302456.09.89.02.zip|home1.movie.sirir.apple.20302456.09.89.03.zip|home1.movie.sirir.apple.20302456.09.89.04.nupkg
        echo "artifacts=$artifacts" >> $GITHUB_OUTPUT

        
      
