name: SomeExecution
run-name: Executing 
on: 
  workflow_dispatch:
    inputs:
      params1:
        description: 'Params1'
        required: false
        default: ''
      params2:
         description: 'Params2'
         required: false
         default: ''

      your_input_name:
        description: 'Description of your input'
        required: true
        default: 'default_value'
jobs:
  MyTest:
    runs-on: ubuntu-latest
    steps:
    - id: Sameple-step
      name: Sample Step
      run: |
        echo "Inputs are "
        echo "${{ inputs.params1 }} ${{ inputs.params2}}"
        echo "${{ inputs.params1   inputs.params2 }} "
        
      
