name: SomeExecution
run-name: Executing 
on: 
  workflow_dispatch
    inputs:
      PARAM1:
        required: true
        type: string
jobs:
  MyTest:
    runs-on: ubuntu-latest
    steps:
    - id: Sameple-step
      name: Sample Step
      run: |
        artifacts=home1.movie.sirir.apple.20302456.09.89.01.zip|home1.movie.sirir.apple.20302456.09.89.02.zip|home1.movie.sirir.apple.20302456.09.89.03.zip|home1.movie.sirir.apple.20302456.09.89.04.nupkg
        echo "artifacts=$artifacts" >> $GITHUB_OUTPUT

        
      
